MLmodel:
    - SeisBench,PhaseNet,original
    # - SeisBench,PhaseNet,stead
    - SeisBench,EQT,original
    # - SeisBench,EQT,stead
    
overlap_ratio: 0.9
    
rescaling: 
    - None
    - 2
    # - 4
    # - 5
    # - 0.5
    # - 4.5
    
frequency: 
    - None  # no filtering
    - [2, 40]  # bandpass filtering
    # - [5, None]  # highpass filtering

ensemble: max  # max, pca, semblance, mean, median, prod, ...

pick:
    format: dataframe  # None or dataframe or dict or list
    method: threshold  # threshold, max, peak
    P_threshold: 0.3  # None or number
    S_threshold: 0.3  # None or number

output: all  # pick or prob

prob_sampling_rate: None  # None or float/int

data:  # specify the input seismic data information 
    component_input: Z12  # the input data component(s), only required if the input data format is numpy.ndarray
    auto_expend: False  # whether to auto expend the input data if input duration is too short, can be Flase or constant or symmetric (check numpy.pad)



