MLmodel:
    - SeisBench_PhaseNet_original
    # - SeisBench_PhaseNet_stead
    - SeisBench_EQT_original
    # - SeisBench_EQT_stead
    
overlap_ratio: 0.9
    
rescaling: 
    - None
    - 2
    # - 4
    
frequency: 
    - None
    - [2, 40]
    # - [5, 45]

ensemble: max

pick:
    P_threshold: 0.3
    S_threshold: 0.3

output: all  # pick or prob



