MLmodel:
    - SeisBench,PhaseNet,original
    # - SeisBench,PhaseNet,stead
    - SeisBench,EQT,original
    # - SeisBench,EQT,stead
    
overlap_ratio: 0.9
    
rescaling: 
    - None
    - 2
    # - 4
    # - 5
    
frequency: 
    - None
    - [2, 40]
    # - [5, 45]

ensemble: max

pick:
    P_threshold: 0.3
    S_threshold: 0.3

output: all  # pick or prob

prob_sampling_rate: None  # None or float/int

