MLmodel:
    - SeisBench,PhaseNet,original
    # - SeisBench,PhaseNet,stead
    - SeisBench,EQT,original
    # - SeisBench,EQT,stead
    
overlap_ratio: 0.9
    
rescaling: 
    - None
    - 2
    # - 4
    # - 5
    # - 0.5
    # - 4.5
    
frequency: 
    - None
    - [2, 40]
    # - [5, 45]

ensemble: max  # max, pca, semblance, mean, median, prod, ...

pick:
    method: threshold  # threshold, max, peak
    P_threshold: 0.3  # None or number
    S_threshold: 0.3  # None or number

output: all  # pick or prob

prob_sampling_rate: None  # None or float/int

